# Generated by Django 5.0 on 2023-12-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
